# AI-GEN-BEGIN
"""LEUC ?? PostgreSQL ?????????"""
from __future__ import annotations

import json
import re
from datetime import datetime
from pathlib import Path
from zoneinfo import ZoneInfo

# AI-GEN-BEGIN
from pgcompat import (
    PgConnection,
    connect as pg_connect,
    drop_all_tables,
    reset_identity_sequences,
)

DATA_DIR = Path(__file__).resolve().parent / "data"
DB_PATH = DATA_DIR / "leuc.db"  # ?????????? PostgreSQL
# AI-GEN-END
_SEED_ROOT_ID = 1
_SEED_BTIT_ID = 1

try:
    from pypinyin import lazy_pinyin as _lazy_pinyin
except ImportError:  # pragma: no cover
    _lazy_pinyin = None

# ? pypinyin ????????????
_FALLBACK = {
    "?": "zhang", "?": "san", "?": "li", "?": "si", "?": "wang", "?": "qiang",
    "?": "zhao", "?": "min", "?": "chen", "?": "chao", "?": "qian", "?": "qi",
    "?": "zhou", "?": "ba", "?": "wu", "?": "jiu", "?": "pu", "?": "tong",
    "?": "yuan", "?": "gong", "?": "bu", "?": "men", "?": "fu", "?": "ze",
    "?": "ren", "?": "xi", "?": "tong", "?": "guan", "?": "li", "?": "yuan",
    "?": "sun", "?": "li", "?": "cai", "?": "zhuan", "?": "shi",
    "?": "liu", "?": "yi", "?": "chen", "?": "er", "?": "zhao", "?": "liu",
    "?": "xin", "?": "zhou",
}


SCHEMA = """
-- PostgreSQL schema

CREATE TABLE IF NOT EXISTS departments (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  parent_id INTEGER,
  owner_user_id INTEGER,
  leorg_id INTEGER UNIQUE,
  manager_leorg_emp_id INTEGER,
  sort_order INTEGER NOT NULL DEFAULT 0,
  FOREIGN KEY (parent_id) REFERENCES departments(id)
);

CREATE TABLE IF NOT EXISTS users (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username TEXT NOT NULL UNIQUE,
  password TEXT NOT NULL,
  display_name TEXT NOT NULL,
  role TEXT NOT NULL,
  dept_id INTEGER,
  phone TEXT,
  email TEXT,
  itcode TEXT,
  password_expire TEXT,
  account_expire TEXT,
  person_type TEXT NOT NULL DEFAULT 'internal',
  feishu_bound INTEGER DEFAULT 0,
  wecom_bound INTEGER DEFAULT 0,
  face_enrolled INTEGER DEFAULT 0,
  face_enrolled_at TEXT,
  fingerprint_enrolled INTEGER DEFAULT 0,
  fingerprint_enrolled_at TEXT,
  can_proxy_apply INTEGER DEFAULT 0,
  can_set_account_expire INTEGER DEFAULT 0,
  beisen_user_id TEXT,
  status TEXT NOT NULL DEFAULT 'active',
  FOREIGN KEY (dept_id) REFERENCES departments(id)
);

CREATE TABLE IF NOT EXISTS dept_extra_owners (
  dept_id INTEGER NOT NULL,
  user_id INTEGER NOT NULL,
  PRIMARY KEY (dept_id, user_id)
);

CREATE TABLE IF NOT EXISTS systems (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code TEXT NOT NULL UNIQUE,
  name TEXT NOT NULL,
  client_id TEXT NOT NULL UNIQUE,
  client_secret TEXT NOT NULL,
  redirect_uris TEXT NOT NULL DEFAULT '',
  scopes TEXT NOT NULL DEFAULT 'openid profile',
  grant_types TEXT NOT NULL DEFAULT 'authorization_code',
  token_endpoint_auth_method TEXT NOT NULL DEFAULT 'client_secret_post',
  require_pkce INTEGER NOT NULL DEFAULT 1,
  access_mode TEXT NOT NULL DEFAULT 'apply',
  forbid_external INTEGER NOT NULL DEFAULT 0,
  has_sensitive INTEGER NOT NULL DEFAULT 0,
  sso_login_field TEXT NOT NULL DEFAULT 'account_name',
  status TEXT NOT NULL DEFAULT 'enabled',
  is_builtin INTEGER NOT NULL DEFAULT 0,
  owner_user_id INTEGER,
  created_at TEXT
);

-- AI-GEN-BEGIN
CREATE TABLE IF NOT EXISTS system_owners (
  system_id INTEGER NOT NULL,
  user_id INTEGER NOT NULL,
  PRIMARY KEY (system_id, user_id),
  FOREIGN KEY (system_id) REFERENCES systems(id),
  FOREIGN KEY (user_id) REFERENCES users(id)
);
-- AI-GEN-END

CREATE TABLE IF NOT EXISTS user_system_accounts (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id INTEGER NOT NULL,
  system_id INTEGER NOT NULL,
  account_name TEXT NOT NULL,
  account_label TEXT,
  is_default INTEGER DEFAULT 0,
  can_login INTEGER DEFAULT 1,
  has_sensitive INTEGER DEFAULT 0,
  perm_summary TEXT DEFAULT '',
  FOREIGN KEY (user_id) REFERENCES users(id),
  FOREIGN KEY (system_id) REFERENCES systems(id)
);

CREATE TABLE IF NOT EXISTS messages (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  from_user_id INTEGER NOT NULL,
  to_user_id INTEGER NOT NULL,
  title TEXT NOT NULL,
  body TEXT NOT NULL,
  created_at TEXT NOT NULL,
  is_read INTEGER DEFAULT 0,
  msg_type TEXT NOT NULL DEFAULT 'chat',
  ref_type TEXT,
  ref_id INTEGER
);

CREATE TABLE IF NOT EXISTS todos (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  assignee_id INTEGER,
  initiator_id INTEGER,
  title TEXT NOT NULL,
  todo_type TEXT NOT NULL,
  bucket TEXT NOT NULL,
  status TEXT NOT NULL,
  created_at TEXT NOT NULL,
  application_id INTEGER,
  step_order INTEGER,
  meta TEXT,
  remark TEXT
);

CREATE TABLE IF NOT EXISTS approval_chain_steps (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  flow_code TEXT NOT NULL,
  step_order INTEGER NOT NULL,
  step_key TEXT NOT NULL,
  step_label TEXT NOT NULL,
  assignee_user_id INTEGER,
  enabled INTEGER DEFAULT 1
);

-- AI-GEN-BEGIN
-- ?????????????????????????
CREATE TABLE IF NOT EXISTS approval_chain_dept_overrides (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  flow_code TEXT NOT NULL,
  step_key TEXT NOT NULL,
  dept_id INTEGER NOT NULL,
  assignee_user_id INTEGER NOT NULL,
  UNIQUE(flow_code, step_key, dept_id)
);
-- AI-GEN-END

CREATE TABLE IF NOT EXISTS sensitive_perm_defs (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  system_id INTEGER NOT NULL,
  perm_code TEXT NOT NULL,
  perm_name TEXT NOT NULL,
  description TEXT DEFAULT '',
  parent_id INTEGER,
  is_sensitive INTEGER NOT NULL DEFAULT 1,
  enabled INTEGER DEFAULT 1,
  FOREIGN KEY (system_id) REFERENCES systems(id)
);

CREATE TABLE IF NOT EXISTS applications (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  flow_code TEXT NOT NULL,
  applicant_id INTEGER NOT NULL,
  perm_def_id INTEGER,
  system_id INTEGER,
  title TEXT NOT NULL,
  status TEXT NOT NULL,
  current_step INTEGER DEFAULT 1,
  total_steps INTEGER DEFAULT 1,
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL,
  provisioned INTEGER DEFAULT 0
);

CREATE TABLE IF NOT EXISTS application_steps (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  application_id INTEGER NOT NULL,
  step_order INTEGER NOT NULL,
  step_key TEXT NOT NULL,
  step_label TEXT NOT NULL,
  assignee_id INTEGER,
  status TEXT NOT NULL,
  todo_id INTEGER,
  decided_at TEXT,
  remark TEXT
);

CREATE TABLE IF NOT EXISTS login_risk (
  username TEXT PRIMARY KEY,
  fail_count INTEGER DEFAULT 0,
  updated_at TEXT
);

CREATE TABLE IF NOT EXISTS reset_codes (
  account TEXT PRIMARY KEY,
  channel TEXT NOT NULL,
  code TEXT NOT NULL,
  created_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS user_fingerprints (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id INTEGER NOT NULL,
  label TEXT NOT NULL,
  enrolled_at TEXT NOT NULL,
  FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE TABLE IF NOT EXISTS role_menus (
  role TEXT NOT NULL,
  menu_id TEXT NOT NULL,
  PRIMARY KEY (role, menu_id)
);

CREATE TABLE IF NOT EXISTS role_caps (
  role TEXT NOT NULL,
  cap_id TEXT NOT NULL,
  PRIMARY KEY (role, cap_id)
);

CREATE TABLE IF NOT EXISTS roles (
  code TEXT PRIMARY KEY,
  label TEXT NOT NULL,
  is_builtin INTEGER NOT NULL DEFAULT 0,
  sort_order INTEGER NOT NULL DEFAULT 100,
  created_at TEXT
);

CREATE TABLE IF NOT EXISTS user_roles (
  user_id INTEGER NOT NULL,
  role TEXT NOT NULL,
  PRIMARY KEY (user_id, role),
  FOREIGN KEY (user_id) REFERENCES users(id),
  FOREIGN KEY (role) REFERENCES roles(code)
);

CREATE TABLE IF NOT EXISTS oauth_codes (
  code TEXT PRIMARY KEY,
  client_id TEXT NOT NULL,
  user_id INTEGER NOT NULL,
  account_id INTEGER,
  redirect_uri TEXT NOT NULL,
  scope TEXT,
  nonce TEXT,
  code_challenge TEXT,
  code_challenge_method TEXT,
  expires_at TEXT NOT NULL,
  used INTEGER DEFAULT 0
);

CREATE TABLE IF NOT EXISTS oauth_tokens (
  access_token TEXT PRIMARY KEY,
  refresh_token TEXT,
  client_id TEXT NOT NULL,
  user_id INTEGER NOT NULL,
  account_id INTEGER,
  scope TEXT,
  expires_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS hr_sync_roster (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  display_name TEXT NOT NULL,
  dept_id INTEGER NOT NULL,
  phone TEXT,
  email TEXT,
  emp_no TEXT,
  leorg_emp_id INTEGER,
  beisen_user_id TEXT,
  source TEXT DEFAULT 'org_sync',
  status TEXT NOT NULL DEFAULT 'pending',
  created_user_id INTEGER,
  synced_at TEXT
);

CREATE TABLE IF NOT EXISTS leorg_sync_state (
  id INTEGER PRIMARY KEY CHECK (id = 1),
  last_mode TEXT,
  last_full_at TEXT,
  last_incr_at TEXT,
  last_change_id INTEGER DEFAULT 0,
  org_mapped INTEGER DEFAULT 0,
  emp_touched INTEGER DEFAULT 0,
  updated_at TEXT
);

CREATE TABLE IF NOT EXISTS system_accounts (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  system_id INTEGER NOT NULL,
  account_uid TEXT,
  account_name TEXT NOT NULL,
  display_name TEXT,
  phone TEXT,
  email TEXT,
  itcode TEXT,
  status TEXT NOT NULL DEFAULT 'unbound',
  leuc_user_id INTEGER,
  source TEXT DEFAULT 'manual',
  created_at TEXT,
  FOREIGN KEY (system_id) REFERENCES systems(id),
  FOREIGN KEY (leuc_user_id) REFERENCES users(id)
);

CREATE TABLE IF NOT EXISTS grant_applications (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  requester_id INTEGER NOT NULL,
  system_id INTEGER NOT NULL,
  leuc_user_id INTEGER NOT NULL,
  status TEXT NOT NULL DEFAULT 'pending',
  suggested_account_id INTEGER,
  bound_account_id INTEGER,
  match_hints TEXT,
  created_at TEXT NOT NULL,
  decided_at TEXT,
  todo_id INTEGER,
  FOREIGN KEY (system_id) REFERENCES systems(id),
  FOREIGN KEY (leuc_user_id) REFERENCES users(id)
);

CREATE TABLE IF NOT EXISTS oa_forms (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  form_type TEXT NOT NULL,
  oa_form_no TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT 'received',
  title TEXT,
  applicant_name TEXT,
  oa_person_code TEXT,
  leuc_user_id INTEGER,
  approved_at TEXT,
  created_at TEXT NOT NULL,
  remark TEXT
);

CREATE TABLE IF NOT EXISTS oa_form_lines (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  form_id INTEGER NOT NULL,
  system_id INTEGER,
  system_code TEXT,
  system_name TEXT,
  req_category TEXT,
  system_entity TEXT,
  applicant_name TEXT,
  applicant_job TEXT,
  oa_person_code TEXT,
  handle_status TEXT NOT NULL DEFAULT 'pending',
  todo_id INTEGER,
  grant_id INTEGER,
  remark TEXT,
  FOREIGN KEY (form_id) REFERENCES oa_forms(id)
);
"""


def name_to_pinyin(display_name: str) -> str:
    name = (display_name or "").strip()
    if not name:
        return "user"
    if _lazy_pinyin:
        raw = "".join(_lazy_pinyin(name))
    else:
        raw = "".join(_FALLBACK.get(ch, ch if re.match(r"[A-Za-z0-9]", ch) else "") for ch in name)
    raw = re.sub(r"[^a-zA-Z0-9]", "", raw).lower()
    return raw or "user"


def alloc_username(conn: PgConnection, display_name: str) -> str:
    """??????????? 1?2? ????????"""
    base = name_to_pinyin(display_name)
    exists = conn.execute("SELECT 1 FROM users WHERE username = ?", (base,)).fetchone()
    if not exists:
        return base
    n = 1
    while True:
        cand = f"{base}{n}"
        if not conn.execute("SELECT 1 FROM users WHERE username = ?", (cand,)).fetchone():
            return cand
        n += 1


# AI-GEN-BEGIN
def normalize_username(username: str) -> str:
    raw = (username or "").strip().lower()
    return re.sub(r"[^a-z0-9_]", "", raw)


def ensure_username_available(
    conn: PgConnection, username: str, exclude_user_id: int | None = None
) -> tuple[bool, str]:
    """????????????????????? (ok, error_or_username)?"""
    uname = normalize_username(username)
    if not uname:
        return False, "???????????????????"
    if exclude_user_id:
        row = conn.execute(
            "SELECT 1 FROM users WHERE username = ? AND id != ?",
            (uname, exclude_user_id),
        ).fetchone()
    else:
        row = conn.execute(
            "SELECT 1 FROM users WHERE username = ?", (uname,)
        ).fetchone()
    if row:
        return False, f"??? {uname} ????"
    return True, uname
# AI-GEN-END


def preview_unique_usernames(
    conn: PgConnection, display_names: list[str]
) -> list[dict]:
    """????????????????????"""
    taken = {r[0] for r in conn.execute("SELECT username FROM users").fetchall()}
    out = []
    for name in display_names:
        base = name_to_pinyin(name)
        cand = base
        n = 1
        while cand in taken:
            cand = f"{base}{n}"
            n += 1
        taken.add(cand)
        out.append(
            {
                "display_name": name,
                "pinyin_base": base,
                "username_preview": cand,
                "will_suffix": cand != base,
            }
        )
    return out


def connect() -> PgConnection:
    # AI-GEN-BEGIN
    DATA_DIR.mkdir(parents=True, exist_ok=True)
    return pg_connect()
    # AI-GEN-END


def _table_cols(conn: PgConnection, table: str) -> set[str]:
    return {r[1] for r in conn.execute(f"PRAGMA table_info({table})").fetchall()}


def migrate_schema(conn: PgConnection) -> None:
    """??????CREATE IF NOT EXISTS ????????"""
    # AI-GEN-BEGIN
    dept_cols = _table_cols(conn, "departments")
    if dept_cols and "leorg_id" not in dept_cols:
        conn.execute("ALTER TABLE departments ADD COLUMN leorg_id INTEGER")
        try:
            conn.execute(
                "CREATE UNIQUE INDEX IF NOT EXISTS idx_departments_leorg_id "
                "ON departments(leorg_id) WHERE leorg_id IS NOT NULL"
            )
        except Exception:
            pass
    # AI-GEN-BEGIN
    if dept_cols and "manager_leorg_emp_id" not in dept_cols:
        conn.execute(
            "ALTER TABLE departments ADD COLUMN manager_leorg_emp_id INTEGER"
        )
    # AI-GEN-BEGIN
    dept_cols = _table_cols(conn, "departments")
    if dept_cols and "sort_order" not in dept_cols:
        conn.execute(
            "ALTER TABLE departments ADD COLUMN sort_order INTEGER NOT NULL DEFAULT 0"
        )
        conn.execute("UPDATE departments SET sort_order = id WHERE sort_order = 0 OR sort_order IS NULL")
    # AI-GEN-END
    # AI-GEN-END
    roster_cols = _table_cols(conn, "hr_sync_roster")
    if roster_cols and "leorg_emp_id" not in roster_cols:
        conn.execute("ALTER TABLE hr_sync_roster ADD COLUMN leorg_emp_id INTEGER")
    if roster_cols and "beisen_user_id" not in roster_cols:
        conn.execute("ALTER TABLE hr_sync_roster ADD COLUMN beisen_user_id TEXT")
    user_cols = _table_cols(conn, "users")
    if user_cols and "leorg_emp_id" not in user_cols:
        conn.execute("ALTER TABLE users ADD COLUMN leorg_emp_id INTEGER")
        try:
            conn.execute(
                "CREATE UNIQUE INDEX IF NOT EXISTS idx_users_leorg_emp_id "
                "ON users(leorg_emp_id) WHERE leorg_emp_id IS NOT NULL"
            )
        except Exception:
            pass
    if user_cols and "beisen_user_id" not in user_cols:
        conn.execute("ALTER TABLE users ADD COLUMN beisen_user_id TEXT")
        try:
            conn.execute(
                "CREATE UNIQUE INDEX IF NOT EXISTS idx_users_beisen_user_id "
                "ON users(beisen_user_id) WHERE beisen_user_id IS NOT NULL "
                "AND beisen_user_id != ''"
            )
        except Exception:
            pass
    # AI-GEN-BEGIN
    sa_cols = _table_cols(conn, "system_accounts")
    if sa_cols and "account_uid" not in sa_cols:
        conn.execute("ALTER TABLE system_accounts ADD COLUMN account_uid TEXT")
    # ???? account_name ??????????????? #id
    if sa_cols or "account_uid" in (_table_cols(conn, "system_accounts") or []):
        rows = conn.execute(
            """SELECT id, system_id, account_name, account_uid FROM system_accounts
            WHERE account_uid IS NULL OR account_uid = ''"""
        ).fetchall()
        for r in rows:
            base = (r["account_name"] or f"acct-{r['id']}").strip()
            uid = base
            clash = conn.execute(
                """SELECT id FROM system_accounts
                WHERE system_id = ? AND account_uid = ? AND id != ? LIMIT 1""",
                (r["system_id"], uid, r["id"]),
            ).fetchone()
            if clash:
                uid = f"{base}#{r['id']}"
            conn.execute(
                "UPDATE system_accounts SET account_uid = ? WHERE id = ?",
                (uid, r["id"]),
            )
        try:
            conn.execute(
                "CREATE UNIQUE INDEX IF NOT EXISTS idx_system_accounts_uid "
                "ON system_accounts(system_id, account_uid) "
                "WHERE account_uid IS NOT NULL AND account_uid != ''"
            )
        except Exception:
            pass
    # AI-GEN-BEGIN
    # ??? SSO ?????account_uid / account_name / email / phone / itcode
    sys_cols = _table_cols(conn, "systems")
    sso_field_just_added = bool(sys_cols and "sso_login_field" not in sys_cols)
    if sso_field_just_added:
        conn.execute(
            "ALTER TABLE systems ADD COLUMN sso_login_field TEXT NOT NULL DEFAULT 'account_name'"
        )
    if sys_cols or "sso_login_field" in (_table_cols(conn, "systems") or []):
        # ????????account_uid??????
        if sso_field_just_added:
            conn.execute(
                "UPDATE systems SET sso_login_field = 'account_uid' WHERE code = 'beisen'"
            )
        conn.execute(
            """UPDATE systems SET sso_login_field = CASE
              WHEN code = 'beisen' THEN 'account_uid' ELSE 'account_name' END
            WHERE sso_login_field IS NULL OR sso_login_field = ''"""
        )
    # AI-GEN-END
    conn.execute(
        """CREATE TABLE IF NOT EXISTS leorg_sync_state (
          id INTEGER PRIMARY KEY CHECK (id = 1),
          last_mode TEXT,
          last_full_at TEXT,
          last_incr_at TEXT,
          last_change_id INTEGER DEFAULT 0,
          org_mapped INTEGER DEFAULT 0,
          emp_touched INTEGER DEFAULT 0,
          updated_at TEXT
        )"""
    )
    # AI-GEN-BEGIN
    conn.execute(
        """CREATE TABLE IF NOT EXISTS roles (
          code TEXT PRIMARY KEY,
          label TEXT NOT NULL,
          is_builtin INTEGER NOT NULL DEFAULT 0,
          sort_order INTEGER NOT NULL DEFAULT 100,
          created_at TEXT
        )"""
    )
    ensure_roles_seeded(conn)
    # AI-GEN-BEGIN
    conn.execute(
        """CREATE TABLE IF NOT EXISTS user_roles (
          user_id INTEGER NOT NULL,
          role TEXT NOT NULL,
          PRIMARY KEY (user_id, role),
          FOREIGN KEY (user_id) REFERENCES users(id),
          FOREIGN KEY (role) REFERENCES roles(code)
        )"""
    )
    ensure_user_roles_migrated(conn)
    # AI-GEN-END
    # AI-GEN-BEGIN
    user_cols2 = _table_cols(conn, "users")
    if user_cols2 and "status" not in user_cols2:
        conn.execute(
            "ALTER TABLE users ADD COLUMN status TEXT NOT NULL DEFAULT 'active'"
        )
    sys_cols2 = _table_cols(conn, "systems")
    if sys_cols2 and "is_builtin" not in sys_cols2:
        conn.execute(
            "ALTER TABLE systems ADD COLUMN is_builtin INTEGER NOT NULL DEFAULT 0"
        )
    ensure_leuc_system(conn)
    # AI-GEN-BEGIN
    msg_cols = _table_cols(conn, "messages")
    if msg_cols and "ref_type" not in msg_cols:
        conn.execute("ALTER TABLE messages ADD COLUMN ref_type TEXT")
    if msg_cols and "ref_id" not in msg_cols:
        conn.execute("ALTER TABLE messages ADD COLUMN ref_id INTEGER")
    # AI-GEN-BEGIN
    todo_cols = _table_cols(conn, "todos")
    if todo_cols and "remark" not in todo_cols:
        conn.execute("ALTER TABLE todos ADD COLUMN remark TEXT")
    step_cols = _table_cols(conn, "application_steps")
    if step_cols and "remark" not in step_cols:
        conn.execute("ALTER TABLE application_steps ADD COLUMN remark TEXT")
    # AI-GEN-END
    ensure_todo_notify_trigger(conn)
    # AI-GEN-BEGIN
    conn.execute(
        """CREATE TABLE IF NOT EXISTS leorg_sync_draft (
          id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          created_by INTEGER,
          mode TEXT,
          max_change_id INTEGER DEFAULT 0,
          changes_json TEXT NOT NULL,
          created_at TEXT
        )"""
    )
    # AI-GEN-END
    # AI-GEN-BEGIN
    from leuc_ops import ensure_ops_tables

    ensure_ops_tables(conn)
    ensure_leuc_apply_perms(conn)
    # ????????? / ??????
    for role, mid in (
        ("super_admin", "admin_tasks"),
        ("super_admin", "admin_notify"),
        ("super_admin", "admin_audit"),
        ("hr_specialist", "admin_tasks"),
        ("hr_specialist", "admin_notify"),
        ("hr_specialist", "admin_audit"),
    ):
        conn.execute(
            "INSERT OR IGNORE INTO role_menus (role, menu_id) VALUES (?, ?)",
            (role, mid),
        )
    # AI-GEN-END
    # AI-GEN-END


# AI-GEN-BEGIN
LEUC_SYSTEM_CODE = "leuc"


# AI-GEN-BEGIN
def ensure_leuc_apply_perms(conn: PgConnection) -> None:
    """????LEUC???????????????????"""
    ensure_leuc_system(conn)
    leuc = conn.execute(
        "SELECT id FROM systems WHERE code = ?", (LEUC_SYSTEM_CODE,)
    ).fetchone()
    if not leuc:
        return
    sid = int(leuc["id"])
    # ????? + ???????????
    conn.execute(
        """UPDATE systems SET access_mode = 'apply', has_sensitive = 1
        WHERE id = ? AND is_builtin = 1""",
        (sid,),
    )
    defs = [
        ("leuc_menu_home", "????", 0, None),
        ("leuc_menu_security", "????/????", 0, None),
        ("leuc_menu_todo", "????", 0, None),
        ("leuc_menu_apply", "????", 0, None),
        ("leuc_menu_org", "?????", 0, None),
        ("leuc_cap_org_sync", "???????", 1, None),
        ("leuc_cap_manage_systems", "??????", 1, None),
        ("leuc_cap_config_roles", "??????", 1, None),
    ]
    for code, name, sens, parent in defs:
        exists = conn.execute(
            "SELECT id FROM sensitive_perm_defs WHERE system_id = ? AND perm_code = ?",
            (sid, code),
        ).fetchone()
        if exists:
            continue
        conn.execute(
            """INSERT INTO sensitive_perm_defs
            (system_id, perm_code, perm_name, description, parent_id, is_sensitive, enabled)
            VALUES (?,?,?,?,?,?,1)""",
            (sid, code, name, f"??????{name}", parent, sens),
        )
# AI-GEN-END


def ensure_todo_notify_trigger(conn: PgConnection) -> None:
    """?? pending ???????????????????"""
    # AI-GEN-BEGIN
    conn.execute("DROP TRIGGER IF EXISTS todos_notify_pending ON todos")
    conn.execute("DROP FUNCTION IF EXISTS leuc_todos_notify_pending()")
    conn.execute(
        """
        CREATE OR REPLACE FUNCTION leuc_todos_notify_pending()
        RETURNS trigger AS $$
        BEGIN
          IF NEW.bucket = 'pending' AND NEW.assignee_id IS NOT NULL THEN
            INSERT INTO messages
              (from_user_id, to_user_id, title, body, created_at, is_read, msg_type, ref_type, ref_id)
            VALUES (
              0,
              NEW.assignee_id,
              '???' || NEW.todo_type,
              '??????' || NEW.title || '???????',
              to_char(NOW() AT TIME ZONE 'Asia/Shanghai', 'YYYY-MM-DD HH24:MI:SS'),
              0,
              'system',
              'todo',
              NEW.id
            );
          END IF;
          RETURN NEW;
        END;
        $$ LANGUAGE plpgsql
        """
    )
    conn.execute(
        """
        CREATE TRIGGER todos_notify_pending
        AFTER INSERT ON todos
        FOR EACH ROW
        EXECUTE FUNCTION leuc_todos_notify_pending()
        """
    )
    # AI-GEN-END


def ensure_leuc_system(conn: PgConnection) -> None:
    """??????LEUC??????????????/?????"""
    # AI-GEN-BEGIN
    now = datetime.now(ZoneInfo("Asia/Shanghai")).strftime("%Y-%m-%dT%H:%M:%S")
    # AI-GEN-END
    row = conn.execute(
        "SELECT id FROM systems WHERE code = ?", (LEUC_SYSTEM_CODE,)
    ).fetchone()
    if row:
        conn.execute(
            """UPDATE systems SET is_builtin = 1, status = 'enabled',
              name = CASE WHEN name IS NULL OR name = '' THEN '????LEUC?' ELSE name END
            WHERE code = ?""",
            (LEUC_SYSTEM_CODE,),
        )
        return
    conn.execute(
        """INSERT INTO systems
        (code, name, client_id, client_secret, redirect_uris, scopes, grant_types,
         token_endpoint_auth_method, require_pkce, access_mode, forbid_external,
         has_sensitive, sso_login_field, status, is_builtin, owner_user_id, created_at)
        VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,1,NULL,?)""",
        (
            LEUC_SYSTEM_CODE,
            "????LEUC?",
            "client_leuc",
            "sk_leuc_builtin_not_for_oidc",
            "",
            "openid profile",
            "authorization_code",
            "client_secret_post",
            0,
            "open",
            0,
            0,
            "account_name",
            "enabled",
            now,
        ),
    )
# AI-GEN-END


# AI-GEN-BEGIN
# ?????code ??????????????????????
BUILTIN_ROLE_DEFS = [
    ("employee", "????", 10),
    ("dept_owner", "?????", 20),
    ("hr_specialist", "????", 30),
    ("system_owner", "?????", 40),
    ("super_admin", "?????", 50),
    ("finance", "??", 60),
]
BUILTIN_ROLE_CODES = {c for c, _, _ in BUILTIN_ROLE_DEFS}


def ensure_roles_seeded(conn: PgConnection) -> None:
    """???????????????????"""
    now = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    for code, label, sort in BUILTIN_ROLE_DEFS:
        conn.execute(
            """INSERT OR IGNORE INTO roles (code, label, is_builtin, sort_order, created_at)
            VALUES (?, ?, 1, ?, ?)""",
            (code, label, sort, now),
        )
    # ???????????????????
    conn.execute(
        "UPDATE roles SET label='?????' WHERE code='dept_owner' AND label='?????'"
    )
    # AI-GEN-BEGIN
    # ??????????????????????
    for role in ("hr_specialist", "system_owner", "super_admin"):
        conn.execute(
            "INSERT OR IGNORE INTO role_menus (role, menu_id) VALUES (?, 'oa_forms')",
            (role,),
        )
    # ?????/??????
    for role in ("super_admin", "hr_specialist", "dept_owner"):
        for cap in ("org_dept_add", "org_dept_delete"):
            conn.execute(
                "INSERT OR IGNORE INTO role_caps (role, cap_id) VALUES (?, ?)",
                (role, cap),
            )
    # AI-GEN-END
    # AI-GEN-BEGIN
    # ????? employee_a ???? user_roles??????????
    for code, label, sort in (
        ("employee_a", "????A", 15),
        ("employee_b", "????B", 16),
    ):
        conn.execute(
            """INSERT OR IGNORE INTO roles (code, label, is_builtin, sort_order, created_at)
            VALUES (?, ?, 1, ?, ?)""",
            (code, label, sort, now),
        )
    # AI-GEN-END


# AI-GEN-BEGIN
EMPLOYEE_ROLE_CODES = frozenset({"employee", "employee_a", "employee_b"})
SYSTEM_ROLE_EXCLUDE = EMPLOYEE_ROLE_CODES  # ??????????????


def ensure_user_roles_migrated(conn: PgConnection) -> None:
    """? users.role ?? user_roles?????"""
    try:
        conn.execute(
            """INSERT OR IGNORE INTO user_roles (user_id, role)
            SELECT id, role FROM users
            WHERE role IS NOT NULL AND role != ''"""
        )
    except Exception:
        pass


def user_roles_of(conn: PgConnection, user_id: int) -> list:
    """?????? code ???? sort_order??"""
    rows = conn.execute(
        """SELECT ur.role FROM user_roles ur
        LEFT JOIN roles r ON r.code = ur.role
        WHERE ur.user_id = ?
        ORDER BY COALESCE(r.sort_order, 999), ur.role""",
        (int(user_id),),
    ).fetchall()
    codes = [r["role"] for r in rows if r["role"]]
    if codes:
        return codes
    # ???????
    u = conn.execute("SELECT role FROM users WHERE id = ?", (int(user_id),)).fetchone()
    if u and u["role"]:
        return [u["role"]]
    return ["employee"]


def sync_primary_role(conn: PgConnection, user_id: int) -> str:
    """? user_roles ?? users.role????????? sort ????? employee?"""
    roles = user_roles_of(conn, user_id)
    primary = "employee"
    for code in roles:
        if code not in EMPLOYEE_ROLE_CODES:
            primary = code
            break
    else:
        if roles:
            primary = roles[0] if roles[0] in EMPLOYEE_ROLE_CODES else "employee"
        else:
            primary = "employee"
            conn.execute(
                "INSERT OR IGNORE INTO user_roles (user_id, role) VALUES (?, 'employee')",
                (int(user_id),),
            )
    conn.execute("UPDATE users SET role = ? WHERE id = ?", (primary, int(user_id)))
    return primary
# AI-GEN-END


def load_role_labels(conn: PgConnection) -> dict:
    try:
        rows = conn.execute(
            "SELECT code, label FROM roles ORDER BY sort_order, code"
        ).fetchall()
        if rows:
            return {r["code"]: r["label"] for r in rows}
    except Exception:
        pass
    return dict(ROLE_LABELS)


def role_label_of(conn: PgConnection, code: str) -> str:
    if not code:
        return ""
    try:
        row = conn.execute("SELECT label FROM roles WHERE code=?", (code,)).fetchone()
        if row:
            return row["label"]
    except Exception:
        pass
    return ROLE_LABELS.get(code, code)
# AI-GEN-END


def backfill_demo_beisen_user_ids(conn: PgConnection) -> None:
    """??????? UserID?????????admin ??? ID?"""
    # AI-GEN-BEGIN
    cols = _table_cols(conn, "users")
    if not cols or "beisen_user_id" not in cols:
        return
    demo_beisen = [
        ("sunli", "6100002"),
        ("zhangcai", "6100003"),
        ("zhaomin", "6100004"),
        ("liufang", "6100005"),
        ("huangwei", "6100006"),
        ("zhangsan", "6100101"),
        ("lisi", "6100102"),
        ("wangqiang", "6100103"),
        ("wujiu", "6100109"),
        ("xuhaohao", "6100201"),
    ]
    for uname, bid in demo_beisen:
        conn.execute(
            """UPDATE users SET beisen_user_id = ?
            WHERE username = ? AND (beisen_user_id IS NULL OR beisen_user_id = '')""",
            (bid, uname),
        )
    # AI-GEN-END


def init_db(force: bool = False) -> None:
    # AI-GEN-BEGIN
    conn = connect()
    if force:
        drop_all_tables(conn)
    conn.executescript(SCHEMA)
    migrate_schema(conn)
    n = conn.execute("SELECT COUNT(*) AS c FROM users").fetchone()["c"]
    # ?????????? migrate ???????????????
    if n == 0:
        seed(conn)
    try:
        conn.execute("ALTER TABLE todos ENABLE TRIGGER todos_notify_pending")
    except Exception:
        pass
    backfill_demo_beisen_user_ids(conn)
    reset_identity_sequences(conn)
    conn.commit()
    conn.close()
    # AI-GEN-END


def seed(conn: PgConnection) -> None:
    # AI-GEN-BEGIN
    # ???????/??? LeOrg ??????????????? admin??????
    root_id = None
    btit_id = None
    # AI-GEN-BEGIN
    # ?????? id ????????????? messages ????
    try:
        conn.execute("ALTER TABLE todos DISABLE TRIGGER todos_notify_pending")
    except Exception:
        pass
    # AI-GEN-END
    # ????????????????????
    conn.execute(
        """INSERT INTO users
        (id, username, password, display_name, role, dept_id, phone, email, itcode,
         password_expire, account_expire, feishu_bound, wecom_bound,
         face_enrolled, fingerprint_enrolled, person_type,
         can_proxy_apply, can_set_account_expire, beisen_user_id, leorg_emp_id)
        VALUES (1, 'admin', '123456', '?????', 'super_admin', NULL, NULL, NULL, 'admin',
                '2099-12-31', NULL, 0, 0, 0, 0, 'internal', 1, 1, NULL, NULL)"""
    )
    # AI-GEN-END
    # ?????? / ????????????
    menu_rows = []
    for role, menus in DEFAULT_ROLE_MENUS.items():
        for mid in menus:
            menu_rows.append((role, mid))
    conn.executemany("INSERT OR IGNORE INTO role_menus (role, menu_id) VALUES (?,?)", menu_rows)
    cap_rows = []
    for role, caps in DEFAULT_ROLE_CAPS.items():
        for cap in caps:
            cap_rows.append((role, cap))
    if cap_rows:
        conn.executemany("INSERT OR IGNORE INTO role_caps (role, cap_id) VALUES (?,?)", cap_rows)
    ensure_roles_seeded(conn)
    # ???????????????? LeOrg ?????
    # AI-GEN-BEGIN
    gaojia = None
    chang = None
    # AI-GEN-END
    global _SEED_ROOT_ID, _SEED_BTIT_ID
    _SEED_ROOT_ID = root_id
    _SEED_BTIT_ID = btit_id
    # AI-GEN-END

    conn.execute(
        """INSERT INTO messages (id, from_user_id, to_user_id, title, body, created_at, is_read, msg_type)
        VALUES
        (1, 0, 1, '????', '???? LEUC??? admin / 123456 ???? LeOrg ?????', '2026-08-04 09:00:00', 0, 'system')
        """
    )

    # OIDC ?????????????????? app=code ???
    now = "2026-08-04T12:00:00"
    portal_cb = "http://127.0.0.1:5055/demo/home/callback"
    # AI-GEN-BEGIN
    # migrate ????? leuc????????????????
    # AI-GEN-BEGIN
    for _sql in (
        "DELETE FROM sensitive_perm_defs",
        "DELETE FROM user_system_accounts",
        "DELETE FROM system_accounts",
        "DELETE FROM system_owners",
        "DELETE FROM grant_applications",
        "DELETE FROM oa_form_lines",
        "DELETE FROM oa_forms",
        "DELETE FROM systems",
    ):
        try:
            conn.execute(_sql)
        except Exception:
            pass
    # AI-GEN-END
    # ?? sso_login_field???? account_uid???? account_name
    systems = [
        # access_mode; forbid_external; has_sensitive; sso_login_field; is_builtin
        (1, "oa", "OA ??", "client_oa", "sk_oa_demo_secret", f"{portal_cb}?app=oa", "openid profile email", "authorization_code", "client_secret_post", 1, "apply", 0, 0, "account_name", "enabled", 0, None, now),
        (2, "bip", "BIP", "client_bip", "sk_bip_demo_secret", f"{portal_cb}?app=bip", "openid profile", "authorization_code", "client_secret_post", 1, "open", 0, 0, "account_name", "enabled", 0, None, now),
        (3, "laiku_erp", "??ERP", "client_laiku_erp", "sk_laiku_erp_secret", f"{portal_cb}?app=laiku_erp", "openid profile", "authorization_code", "client_secret_post", 1, "apply", 0, 1, "account_name", "enabled", 0, None, now),
        (4, "keji_erp", "??ERP", "client_keji_erp", "sk_keji_erp_secret", f"{portal_cb}?app=keji_erp", "openid profile", "authorization_code", "client_secret_post", 1, "apply", 0, 1, "account_name", "enabled", 0, None, now),
        (5, "beisen", "??", "client_beisen", "sk_beisen_demo_secret", f"{portal_cb}?app=beisen", "openid profile", "authorization_code", "client_secret_post", 1, "apply", 1, 1, "account_uid", "enabled", 0, None, now),
        (6, "feishu", "??", "client_feishu", "sk_feishu_demo_secret", f"{portal_cb}?app=feishu", "openid profile", "authorization_code", "client_secret_post", 1, "apply", 1, 0, "account_name", "enabled", 0, None, now),
        (7, "leuc", "????LEUC?", "client_leuc", "sk_leuc_builtin_not_for_oidc", "", "openid profile", "authorization_code", "client_secret_post", 0, "open", 0, 0, "account_name", "enabled", 1, None, now),
    ]
    conn.executemany(
        """INSERT INTO systems
        (id, code, name, client_id, client_secret, redirect_uris, scopes, grant_types,
         token_endpoint_auth_method, require_pkce, access_mode, forbid_external, has_sensitive,
         sso_login_field, status, is_builtin, owner_user_id, created_at)
        VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)""",
        systems,
    )
    # AI-GEN-END
    # AI-GEN-BEGIN
    # ????????????????/????
    # AI-GEN-END

    # ??????????????
    accounts = [
        (1, 1, 3, "admin_laiku", "????", 1, 1, 1, "?????"),
        (2, 1, 4, "admin_keji", "????", 1, 1, 1, "?????"),
        (3, 1, 1, "admin_oa", "??OA", 1, 1, 0, "??"),
    ]
    conn.executemany(
        """INSERT INTO user_system_accounts
        (id, user_id, system_id, account_name, account_label, is_default, can_login, has_sensitive, perm_summary)
        VALUES (?,?,?,?,?,?,?,?,?)""",
        accounts,
    )
    # ????????ERP??????????????
    # AI-GEN-BEGIN
    # AI-GEN-END

    # ??/?????????? ? ???? ? ??????=??????????
    conn.executemany(
        """INSERT INTO approval_chain_steps
        (id, flow_code, step_order, step_key, step_label, assignee_user_id, enabled)
        VALUES (?,?,?,?,?,?,?)""",
        [
            (1, "sensitive", 1, "direct_leader", "????", None, 1),
            (2, "sensitive", 2, "level1_leader", "????", None, 1),
            (3, "sensitive", 3, "finance", "??", (chang["id"] if chang else 1), 1),
            (4, "external", 1, "direct_leader", "????", None, 1),
            (5, "external", 2, "level1_leader", "????", None, 1),
            (6, "external", 3, "finance", "??", (chang["id"] if chang else 1), 1),
        ],
    )
    # ????????????/???????????????????
    conn.executemany(
        """INSERT INTO sensitive_perm_defs
        (id, system_id, perm_code, perm_name, description, parent_id, is_sensitive, enabled)
        VALUES (?,?,?,?,?,?,?,?)""",
        [
            (1, 3, "biz_root", "????", "??ERP?????", None, 0, 1),
            (2, 3, "order_edit", "????", "????", 1, 0, 1),
            (3, 3, "cost_view", "????", "??ERP????", 1, 0, 1),
            (4, 3, "audit_ro", "????", "??ERP????", 1, 0, 1),
            (5, 4, "kj_root", "????", "??ERP???", None, 0, 1),
            (6, 4, "cost_query", "????", "??ERP??", 5, 0, 1),
            (7, 5, "hr_root", "????", "???????", None, 0, 1),
            (8, 5, "salary_view", "????", "????", 7, 0, 1),
            (9, 1, "oa_root", "OA??", "OA???", None, 0, 1),
            (10, 1, "oa_approve", "????", "OA??", 9, 0, 1),
        ],
    )

    # AI-GEN-BEGIN
    # ????????????dept_id ??????? LeOrg ???????
    if _SEED_ROOT_ID is not None and _SEED_BTIT_ID is not None:
        conn.executemany(
            """INSERT INTO hr_sync_roster
            (id, display_name, dept_id, phone, email, emp_no, source, status)
            VALUES (?,?,?,?,?,?, 'org_sync', 'pending')""",
            [
                (1, "??", _SEED_BTIT_ID, "13910000001", "liuyi@lecoo.com", "E1001"),
                (2, "??", _SEED_BTIT_ID, "13910000002", "chener@lecoo.com", "E1002"),
                (3, "??", _SEED_BTIT_ID, "13910000003", "zhangsan.new@lecoo.com", "E1003"),
                (4, "??", _SEED_BTIT_ID, "13910000004", "zhaoliu@lecoo.com", "E1004"),
                (5, "??", _SEED_ROOT_ID, "13910000005", "sunli2@lecoo.com", "E1005"),
            ],
        )
    # AI-GEN-END

    # ??????????/???????????????
    now_d = "2026-08-04"
    # AI-GEN-BEGIN
    conn.executemany(
        """INSERT INTO system_accounts
        (id, system_id, account_uid, account_name, display_name, phone, email, itcode, status, leuc_user_id, source, created_at)
        VALUES (?,?,?,?,?,?,?,?,?,?,?,?)""",
        [
            (1, 3, "ERP-LY-001", "liuyi_erp", "??", "13910000001", "liuyi@lecoo.com", "liuyi", "unbound", None, "sync", now_d),
            (2, 3, "ERP-CE-001", "chener01", "??", "13910000002", "chener@lecoo.com", None, "unbound", None, "import", now_d),
            (3, 4, "KJ-ZL-001", "zhaoliu_kj", "??", None, "zhaoliu@lecoo.com", "zhaoliu", "unbound", None, "sync", now_d),
            (4, 3, "ERP-OR-001", "orphan_erp", "????", "13919999999", "orphan@lecoo.com", "orphan", "unbound", None, "import", now_d),
            # ???account_uid = BeisenUserID????
            (5, 5, "630701809", "beisen_wujiu", "??", "13800000009", "wujiu@lecoo.com", "wujiu", "unbound", None, "sync", now_d),
        ],
    )
    # AI-GEN-END

    # AI-GEN-BEGIN
    # ???????????????????
    todos = [
        (1, 1, 1, "? LeOrg ???????", "????", "pending", "open", "2026-08-02", None, None, None),
    ]
    # AI-GEN-END
    conn.executemany(
        """INSERT INTO todos
        (id, assignee_id, initiator_id, title, todo_type, bucket, status, created_at, application_id, step_order, meta)
        VALUES (?,?,?,?,?,?,?,?,?,?,?)""",
        todos,
    )


# AI-GEN-BEGIN
# ??????????????????? role_menus ?
ALL_MENUS = [
    {"id": "home", "label": "????", "group": "??"},
    {"id": "security", "label": "????", "group": "??"},
    {"id": "todo", "label": "????", "group": "??"},
    {"id": "apply", "label": "????", "group": "??"},
    {"id": "my_org", "label": "?????", "group": "??"},
    {"id": "my_systems", "label": "??????", "group": "????"},
    {"id": "sys_accounts", "label": "??????", "group": "????"},
    {"id": "oa_forms", "label": "????", "group": "????"},
    {"id": "admin_tasks", "label": "????", "group": "????"},
    {"id": "admin_notify", "label": "????", "group": "????"},
    {"id": "admin_audit", "label": "????", "group": "????"},
    {"id": "admin_sensitive", "label": "?????", "group": "????"},
    {"id": "admin_roles", "label": "?????", "group": "????"},
]

# ????????? + ??????????
EXTERNAL_MENUS = ["home", "security"]

# ????????????? role_caps?
ALL_BUTTONS = [
    {"id": "manage_all_org", "label": "??????", "menu": "my_org"},
    {"id": "org_add", "label": "????", "menu": "my_org"},
    {"id": "org_import", "label": "????", "menu": "my_org"},
    {"id": "org_sync", "label": "????", "menu": "my_org"},
    {"id": "org_set_owner", "label": "???????", "menu": "my_org"},
    {"id": "org_dept_add", "label": "????", "menu": "my_org"},
    {"id": "org_dept_delete", "label": "????", "menu": "my_org"},
    {"id": "proxy_apply", "label": "??????/??", "menu": "my_org"},
    {"id": "direct_bind", "label": "????", "menu": "my_org"},
    {"id": "set_account_expire", "label": "???????", "menu": "my_org"},
    {"id": "manage_systems", "label": "??????", "menu": "my_systems"},
    {"id": "sys_add", "label": "????", "menu": "my_systems"},
    {"id": "sys_perm_edit", "label": "??????", "menu": "my_systems"},
    {"id": "sys_acct_sync", "label": "??/?????", "menu": "sys_accounts"},
    {"id": "config_roles", "label": "??????/??", "menu": "admin_roles"},
    {"id": "role_assign", "label": "??????", "menu": "admin_roles"},
    {"id": "sensitive_config", "label": "???????", "menu": "admin_sensitive"},
]
ALL_CAPS = ALL_BUTTONS  # ????

# ??????? role_menus???? ROLE_MENUS ???
DEFAULT_ROLE_MENUS = {
    "employee": ["home", "security", "todo", "apply", "my_org"],
    "finance": ["home", "security", "todo", "apply", "my_org"],
    "hr_specialist": [
        "home", "security", "todo", "apply", "my_org", "oa_forms",
        "admin_tasks", "admin_notify", "admin_audit",
    ],
    "system_owner": ["home", "security", "todo", "apply", "my_org", "my_systems", "sys_accounts", "oa_forms"],
    "super_admin": [
        "home", "security", "todo", "apply", "my_org",
        "my_systems", "sys_accounts", "oa_forms",
        "admin_tasks", "admin_notify", "admin_audit",
        "admin_sensitive", "admin_roles",
    ],
    "employee_a": ["home", "security", "todo", "apply", "my_org"],
    "employee_b": ["home", "security", "todo", "apply", "my_org"],
    "dept_owner": ["home", "security", "todo", "apply", "my_org"],
}

DEFAULT_ROLE_CAPS = {
    "employee": [],
    "finance": [],
    "hr_specialist": [
        "manage_all_org", "org_add", "org_import", "org_sync", "org_set_owner",
        "org_dept_add", "org_dept_delete",
        "proxy_apply", "direct_bind", "set_account_expire",
    ],
    "system_owner": ["manage_systems", "sys_perm_edit", "sys_acct_sync"],
    "super_admin": [
        "manage_all_org", "org_add", "org_import", "org_sync", "org_set_owner",
        "org_dept_add", "org_dept_delete",
        "proxy_apply", "direct_bind", "set_account_expire",
        "manage_systems", "sys_add", "sys_perm_edit", "sys_acct_sync",
        "config_roles", "role_assign", "sensitive_config",
    ],
    "dept_owner": [
        "org_add", "org_import", "org_set_owner",
        "org_dept_add", "org_dept_delete",
        "proxy_apply", "set_account_expire",
    ],
}

ROLE_MENUS = DEFAULT_ROLE_MENUS  # ??????????? DB

ROLE_LABELS = {
    "employee": "????",
    "employee_a": "????",
    "employee_b": "????",
    "dept_owner": "?????",
    "hr_specialist": "????",
    "system_owner": "?????",
    "super_admin": "?????",
    "finance": "??",
}
# AI-GEN-END
