# AI-GEN-BEGIN
"""PostgreSQL 连接包装：尽量兼容原 sqlite3 调用方式（? / OR IGNORE / lastrowid / PRAGMA）。"""
from __future__ import annotations

import os
import re
from typing import Any, Iterable, Optional, Sequence

import psycopg
from psycopg.rows import dict_row

DEFAULT_DATABASE_URL = "postgresql://leuc:leuc@127.0.0.1:5432/leuc"

# 无自增 id、INSERT 不应 RETURNING id 的表
_NO_RETURNING_ID = {
    "role_menus",
    "role_caps",
    "user_roles",
    "dept_extra_owners",
    "system_owners",
    "login_risk",
    "reset_codes",
    "oauth_codes",
    "oauth_tokens",
    "roles",
}

_INSERT_RE = re.compile(
    r"^\s*INSERT\s+(?:OR\s+IGNORE\s+)?INTO\s+([\"']?)(\w+)\1",
    re.IGNORECASE | re.DOTALL,
)
_PRAGMA_TABLE_INFO_RE = re.compile(
    r"^\s*PRAGMA\s+table_info\s*\(\s*([\"']?)(\w+)\1\s*\)\s*$",
    re.IGNORECASE,
)


def database_url() -> str:
    return (
        os.environ.get("DATABASE_URL")
        or os.environ.get("LEUC_DATABASE_URL")
        or DEFAULT_DATABASE_URL
    ).strip()


def _qmark_to_percent(sql: str) -> str:
    """把 sqlite 风格 ? 占位符换成 psycopg %s（忽略字符串字面量内的 ?）。"""
    out: list[str] = []
    i = 0
    n = len(sql)
    in_single = False
    in_double = False
    while i < n:
        ch = sql[i]
        if ch == "'" and not in_double:
            # 简单处理 '' 转义
            if in_single and i + 1 < n and sql[i + 1] == "'":
                out.append("''")
                i += 2
                continue
            in_single = not in_single
            out.append(ch)
            i += 1
            continue
        if ch == '"' and not in_single:
            in_double = not in_double
            out.append(ch)
            i += 1
            continue
        if ch == "?" and not in_single and not in_double:
            out.append("%s")
            i += 1
            continue
        out.append(ch)
        i += 1
    return "".join(out)


def rewrite_sql(sql: str) -> str:
    """运行时 SQL 方言转换。"""
    s = sql.strip()
    # sqlite_master → pg_tables
    if re.search(r"\bsqlite_master\b", s, re.I):
        s = re.sub(
            r"SELECT\s+name\s+FROM\s+sqlite_master\s+WHERE\s+type\s*=\s*['\"]table['\"]",
            "SELECT tablename AS name FROM pg_catalog.pg_tables WHERE schemaname = 'public'",
            s,
            flags=re.I,
        )
        s = re.sub(r"\bsqlite_master\b", "pg_catalog.pg_tables", s, flags=re.I)

    # INSERT OR IGNORE → ON CONFLICT DO NOTHING
    if re.match(r"^\s*INSERT\s+OR\s+IGNORE\s+INTO\b", s, re.I):
        s = re.sub(r"^\s*INSERT\s+OR\s+IGNORE\s+INTO\b", "INSERT INTO", s, count=1, flags=re.I)
        if not re.search(r"\bON\s+CONFLICT\b", s, re.I):
            s = s.rstrip().rstrip(";") + " ON CONFLICT DO NOTHING"

    # IFNULL → COALESCE
    s = re.sub(r"\bIFNULL\s*\(", "COALESCE(", s, flags=re.I)

    # DDL: AUTOINCREMENT / INTEGER PRIMARY KEY → IDENTITY
    s = re.sub(
        r"\bINTEGER\s+PRIMARY\s+KEY\s+AUTOINCREMENT\b",
        "INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY",
        s,
        flags=re.I,
    )
    s = re.sub(
        r"\bid\s+INTEGER\s+PRIMARY\s+KEY\b(?!\s+CHECK)",
        "id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY",
        s,
        flags=re.I,
    )
    return s


class PgRow:
    """兼具 dict 键访问与 sqlite Row 的 keys()/下标。"""

    __slots__ = ("_data", "_keys")

    def __init__(self, data: dict):
        self._data = data
        self._keys = list(data.keys())

    def keys(self):
        return self._keys

    def __getitem__(self, key):
        if isinstance(key, int):
            return self._data[self._keys[key]]
        return self._data[key]

    def __contains__(self, key):
        return key in self._data

    def __iter__(self):
        return iter(self._data.values())

    def get(self, key, default=None):
        return self._data.get(key, default)


class PgCursor:
    def __init__(self, rows: list, lastrowid: Any = None, description=None):
        self._rows = rows
        self._idx = 0
        self.lastrowid = lastrowid
        self.description = description
        self.rowcount = len(rows)

    def fetchone(self):
        if self._idx >= len(self._rows):
            return None
        row = self._rows[self._idx]
        self._idx += 1
        return row

    def fetchall(self):
        rest = self._rows[self._idx :]
        self._idx = len(self._rows)
        return rest

    def __iter__(self):
        return iter(self.fetchall())


class PgConnection:
    def __init__(self, raw: psycopg.Connection):
        self._raw = raw
        self.row_factory = None  # 兼容属性

    def execute(self, sql: str, params: Optional[Sequence[Any]] = None) -> PgCursor:
        # PRAGMA table_info(table)
        m = _PRAGMA_TABLE_INFO_RE.match(sql.strip())
        if m:
            table = m.group(2)
            return self._pragma_table_info(table)

        rewritten = rewrite_sql(sql)
        rewritten = _qmark_to_percent(rewritten)
        lastrowid = None

        insert_m = _INSERT_RE.match(rewritten)
        table = insert_m.group(2).lower() if insert_m else None
        want_returning = (
            table
            and table not in _NO_RETURNING_ID
            and not re.search(r"\bRETURNING\b", rewritten, re.I)
            and rewritten.lstrip().upper().startswith("INSERT")
        )
        exec_sql = rewritten
        if want_returning:
            exec_sql = rewritten.rstrip().rstrip(";") + " RETURNING id"

        with self._raw.cursor(row_factory=dict_row) as cur:
            if params is None:
                cur.execute(exec_sql)
            else:
                cur.execute(exec_sql, tuple(params))
            rows: list = []
            if cur.description:
                raw_rows = cur.fetchall()
                if want_returning and raw_rows:
                    lastrowid = raw_rows[0].get("id")
                    # 业务通常只要 lastrowid；若原 SQL 无 RETURNING，不返回行集
                    if not re.search(r"\bRETURNING\b", rewritten, re.I):
                        rows = []
                    else:
                        rows = [PgRow(dict(r)) for r in raw_rows]
                else:
                    rows = [PgRow(dict(r)) for r in raw_rows]
            desc = cur.description
        return PgCursor(rows, lastrowid=lastrowid, description=desc)

    def executemany(self, sql: str, seq_of_params: Iterable[Sequence[Any]]) -> PgCursor:
        rewritten = rewrite_sql(sql)
        rewritten = _qmark_to_percent(rewritten)
        with self._raw.cursor() as cur:
            cur.executemany(rewritten, list(seq_of_params))
        return PgCursor([])

    def executescript(self, script: str) -> None:
        # 去掉行注释后按 ; 拆分
        lines = []
        for line in script.splitlines():
            stripped = line.strip()
            if stripped.startswith("--"):
                continue
            # 行尾 -- 注释
            if "--" in line:
                in_s = False
                buf = []
                j = 0
                while j < len(line):
                    c = line[j]
                    if c == "'":
                        in_s = not in_s
                        buf.append(c)
                        j += 1
                        continue
                    if not in_s and line[j : j + 2] == "--":
                        break
                    buf.append(c)
                    j += 1
                line = "".join(buf)
            lines.append(line)
        text = "\n".join(lines)
        parts = [p.strip() for p in text.split(";") if p.strip()]
        for part in parts:
            self.execute(part)
        self.commit()

    def _pragma_table_info(self, table: str) -> PgCursor:
        with self._raw.cursor() as cur:
            cur.execute(
                """
                SELECT
                  a.attnum - 1 AS cid,
                  a.attname AS name,
                  pg_catalog.format_type(a.atttypid, a.atttypmod) AS type,
                  CASE WHEN a.attnotnull THEN 1 ELSE 0 END AS notnull,
                  pg_get_expr(ad.adbin, ad.adrelid) AS dflt_value,
                  CASE WHEN EXISTS (
                    SELECT 1 FROM pg_constraint c
                    WHERE c.conrelid = a.attrelid AND c.contype = 'p'
                      AND a.attnum = ANY (c.conkey)
                  ) THEN 1 ELSE 0 END AS pk
                FROM pg_attribute a
                JOIN pg_class cls ON cls.oid = a.attrelid
                JOIN pg_namespace ns ON ns.oid = cls.relnamespace
                LEFT JOIN pg_attrdef ad ON ad.adrelid = a.attrelid AND ad.adnum = a.attnum
                WHERE ns.nspname = 'public'
                  AND cls.relname = %s
                  AND a.attnum > 0
                  AND NOT a.attisdropped
                ORDER BY a.attnum
                """,
                (table,),
            )
            rows = [tuple(r) for r in cur.fetchall()]
        return PgCursor(rows)

    def commit(self):
        self._raw.commit()

    def rollback(self):
        self._raw.rollback()

    def close(self):
        self._raw.close()

    def __enter__(self):
        return self

    def __exit__(self, exc_type, exc, tb):
        if exc_type:
            self.rollback()
        else:
            self.commit()
        self.close()
        return False


def connect(url: Optional[str] = None) -> PgConnection:
    raw = psycopg.connect(url or database_url(), autocommit=False)
    return PgConnection(raw)


def drop_all_tables(conn: PgConnection) -> None:
    conn.execute("DROP SCHEMA public CASCADE")
    conn.execute("CREATE SCHEMA public")
    conn.commit()


def reset_identity_sequences(conn: PgConnection) -> None:
    """种子写入显式 id 后，把 IDENTITY/SERIAL 序列校准到 MAX(id)。"""
    cur = conn.execute(
        """
        SELECT c.relname AS table_name
        FROM pg_class c
        JOIN pg_namespace n ON n.oid = c.relnamespace
        WHERE n.nspname = 'public' AND c.relkind = 'r'
        """
    )
    tables = [r["table_name"] if isinstance(r, PgRow) else r[0] for r in cur.fetchall()]
    for table in tables:
        cols = conn.execute(f"PRAGMA table_info({table})").fetchall()
        col_names = {c[1] for c in cols}
        if "id" not in col_names:
            continue
        conn.execute(
            f"""
            DO $$
            DECLARE
              seq regclass;
              max_id bigint;
            BEGIN
              seq := pg_get_serial_sequence('{table}', 'id');
              IF seq IS NULL THEN
                RETURN;
              END IF;
              SELECT MAX(id) INTO max_id FROM {table};
              IF max_id IS NULL THEN
                PERFORM setval(seq, 1, false);
              ELSE
                PERFORM setval(seq, max_id, true);
              END IF;
            END $$;
            """
        )
    conn.commit()


# AI-GEN-END
